project 'BuddyShop.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'BuddyShop' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'OCMapper'
  pod 'AFNetworking'
  pod 'SDWebImage', '~> 4.0'
  pod 'Toast', '~> 4.0.0'

  target 'BuddyShopTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BuddyShopUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
